"use client";
import {useEffect,useMemo,useState} from "react";
import {displayDate,loadTasks,PREF_KEY,Priority,saveTasks,Task,TaskSize,TaskStyle,weekLabel,weekStart} from "@/lib/tasks";import {syncWidgetTasks} from "@/lib/widgetBridge";
type Draft={text:string;due:string;tag:string;notes:string;priority:Priority};
const blank:Draft={text:"",due:"",tag:"",notes:"",priority:"medium"};
export default function HeadRoom(){
 const [tasks,setTasks]=useState<Task[]>([]),[ready,setReady]=useState(false),[draft,setDraft]=useState<Draft>(blank),[editing,setEditing]=useState<Task|null>(null),[modal,setModal]=useState(false),[viewOpen,setViewOpen]=useState(false),[size,setSize]=useState<TaskSize>("default"),[style,setStyle]=useState<TaskStyle>("card"),[collapsed,setCollapsed]=useState<Record<string,boolean>>({});
 useEffect(()=>{setTasks(loadTasks());try{const p=JSON.parse(localStorage.getItem(PREF_KEY)||"{}");if(p.size)setSize(p.size);if(p.style)setStyle(p.style);setCollapsed(p.collapsed||{})}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready){saveTasks(tasks);void syncWidgetTasks(tasks)}},[tasks,ready]);useEffect(()=>{if(ready)localStorage.setItem(PREF_KEY,JSON.stringify({size,style,collapsed}))},[size,style,collapsed,ready]);
 const sorted=useMemo(()=>[...tasks].sort((a,b)=>weekStart(a)-weekStart(b)||Number(a.done)-Number(b.done)),[tasks]);
 const groups=useMemo(()=>{const m=new Map<number,Task[]>();sorted.forEach(t=>{const k=weekStart(t);m.set(k,[...(m.get(k)||[]),t])});return [...m.entries()]},[sorted]);
 const active=tasks.filter(t=>!t.done).length;
 const openAdd=()=>{setEditing(null);setDraft(blank);setModal(true)};const openEdit=(t:Task)=>{setEditing(t);setDraft({text:t.text,due:t.due,tag:t.tag,notes:t.notes,priority:t.priority});setModal(true)};
 const submit=()=>{if(!draft.text.trim())return;if(editing)setTasks(x=>x.map(t=>t.id===editing.id?{...t,...draft,text:draft.text.trim()}:t));else setTasks(x=>[...x,{id:Date.now(),...draft,text:draft.text.trim(),done:false}]);setModal(false)};
 const remove=(id:number)=>{if(confirm("Delete this task?"))setTasks(x=>x.filter(t=>t.id!==id));setModal(false)};
 const toggle=(id:number)=>setTasks(x=>x.map(t=>t.id===id?{...t,done:!t.done}:t));
 const Card=({task}:{task:Task})=><article className={`task ${task.priority} ${task.done?"done":""} ${size} ${style}`} >
   <button className="check" onClick={()=>toggle(task.id)} aria-label={task.done?"Mark active":"Mark complete"}>{task.done?"✓":""}</button><div className="taskBody"><strong className="taskTitle">{task.text}</strong>{size!=="compact"&&<div className="chips">{task.due&&<span>{displayDate(task.due)}</span>}{task.tag&&<span>{task.tag}</span>}<span>{task.priority.toUpperCase()}</span></div>}{size==="expanded"&&task.notes&&<p>{task.notes}</p>}</div><button className="more" onClick={()=>openEdit(task)} aria-label="Edit task">⋮</button>
 </article>;
 const Board=()=> <div className="board">{(["high","medium","low"] as Priority[]).map(p=>{const items=sorted.filter(t=>t.priority===p);return items.length?<section className="lane" key={p}><h2>{p.toUpperCase()} PRIORITY <span>{items.length}</span></h2>{items.map(t=><Card key={t.id} task={t}/>)}</section>:null})}</div>;
 if(!ready)return null;
 return <main><header><div><div className="brand">HEADROOM</div><p>MAKE SPACE. MOVE FORWARD.</p></div><button className="view" onClick={()=>setViewOpen(true)}>VIEW</button></header>
 <div className="sectionTitle"><h1>MY TASKS</h1><span>{active} ACTIVE</span></div>
 {tasks.length===0?<div className="empty"><b>✓</b><h2>Nothing pending</h2><p>Your space is clear. Add something when it matters.</p></div>:style==="board"?<Board/>:<div className="weeks">{groups.map(([start,items])=>{const closed=collapsed[String(start)];return <section className="week" key={start}><button className="weekHead" onClick={()=>setCollapsed(x=>({...x,[String(start)]:!closed}))}><span className="weekLabel"><svg className={closed?"chevron":"chevron open"} viewBox="0 0 24 24" aria-hidden="true"><path d="M9 19L16 12L9 5"/></svg><span>{weekLabel(start)}</span></span><span>{items.length}</span></button>{!closed&&<div className="weekBody">{items.map(t=><Card key={t.id} task={t}/>)}</div>}</section>})}</div>}
 <button className="fab" onClick={openAdd} aria-label="Add task">+</button>
 {modal&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(false)}}><div className="dialog"><h2>{editing?"Edit task":"New task"}</h2><input autoFocus placeholder="Task title" value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})}/><input type="date" value={draft.due} onChange={e=>setDraft({...draft,due:e.target.value})}/><input placeholder="Tag (e.g. Personal)" value={draft.tag} onChange={e=>setDraft({...draft,tag:e.target.value})}/><textarea placeholder="Notes (optional)" value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/><div className="radios">{(["high","medium","low"] as Priority[]).map(p=><label key={p}><input type="radio" name="priority" checked={draft.priority===p} onChange={()=>setDraft({...draft,priority:p})}/>{p[0].toUpperCase()+p.slice(1)}</label>)}</div><div className="actions">{editing&&<button className="danger" onClick={()=>remove(editing.id)}>DELETE</button>}<span/><button onClick={()=>setModal(false)}>CANCEL</button><button className="primary" onClick={submit}>{editing?"SAVE":"ADD"}</button></div></div></div>}
 {viewOpen&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setViewOpen(false)}}><div className="dialog"><h2>View options</h2><label className="fieldLabel">TASK SIZE<select value={size} onChange={e=>setSize(e.target.value as TaskSize)}><option value="compact">Compact</option><option value="default">Default</option><option value="expanded">Expanded</option></select></label><label className="fieldLabel">LAYOUT<select value={style} onChange={e=>setStyle(e.target.value as TaskStyle)}><option value="card">Card</option><option value="list">List</option><option value="board">Board</option></select></label><div className="actions"><span/><button onClick={()=>setViewOpen(false)}>CANCEL</button><button className="primary" onClick={()=>setViewOpen(false)}>APPLY</button></div></div></div>}
 </main>
}